#local project
version: '2'
services:
  docker_web:
    build:
      context: ./
      dockerfile: web_dockerfile
    volumes:
    - ./frontend/build:/var/www/friday
    ports:
    - "3041:80"
  docker_nodejs:
    build:
      context: ./
      dockerfile: node_dockerfile
    volumes:
    - ./backend:/usr/src/backend
    - ./frontend:/usr/src/frontend
    - ./autorun/scripts/node:/usr/src/scripts
    ports:
    - "3042:8080"
    links:
    - docker_mongo
  docker_mongo:
    build:
      context: ./
      dockerfile: mongo_dockerfile
    volumes:
    - ./autorun/dump:/dump
    - ./backup:/backup
    ports:
    - "3043:27017"